/**
* jquery.hoverdir.js v1.1.1
* http://www.codrops.com
*
* Licensed under the MIT license.
* http://www.opensource.org/licenses/mit-license.php
*
* Copyright 2012, Codrops
* http://www.codrops.com
*/
!function(t,o){"use strict";t.HoverDir=function(o,i){this.$el=t(i),this._init(o)},t.HoverDir.defaults={speed:300,easing:"ease",hoverDelay:0,inverse:!1,hoverElem:"div"},t.HoverDir.prototype={_init:function(o){this.options=t.extend(!0,{},t.HoverDir.defaults,o),this.transitionProp="all "+this.options.speed+"ms "+this.options.easing,this.support=Modernizr.csstransitions,this._loadEvents(),0===t("#hoverdir-style").length&&t('<style id="hoverdir-style">.hoverdir-notransition {-webkit-transition: none !important;-moz-transition: none !important;-o-transition: none !important;-ms-transition: none !important;transition: none !important;}</style>').appendTo("body")},_loadEvents:function(){var o=this;this.$el.on("mouseenter.hoverdir, mouseleave.hoverdir",function(i){var e=t(this),n=e.find(o.options.hoverElem),r=o._getDir(e,{x:i.pageX,y:i.pageY}),s=o._getStyle(r);"mouseenter"===i.type?(n.addClass("hoverdir-notransition"),n.hide().css(s.from),n.length&&n[0].offsetHeight,n.removeClass("hoverdir-notransition"),clearTimeout(o.tmhover),o.tmhover=setTimeout(function(){n.show(0,function(){var i=t(this);o.support&&i.css("transition",o.transitionProp),o._applyAnimation(i,s.to,o.options.speed)})},o.options.hoverDelay)):(o.support&&n.css("transition",o.transitionProp),clearTimeout(o.tmhover),o._applyAnimation(n,s.from,o.options.speed))})},_getDir:function(t,o){var i=t.width(),e=t.height(),n=(o.x-t.offset().left-i/2)*(i>e?e/i:1),r=(o.y-t.offset().top-e/2)*(e>i?i/e:1),s=Math.round((Math.atan2(r,n)*(180/Math.PI)+180)/90+3)%4;return s},_getStyle:function(t){var o,i,e={left:"0px",top:"-100%"},n={left:"0px",top:"100%"},r={left:"-100%",top:"0px"},s={left:"100%",top:"0px"},a={top:"0px"},p={left:"0px"};switch(t){case 0:o=this.options.inverse?n:e,i=a;break;case 1:o=this.options.inverse?r:s,i=p;break;case 2:o=this.options.inverse?e:n,i=a;break;case 3:o=this.options.inverse?s:r,i=p}return{from:o,to:i}},_applyAnimation:function(o,i,e){t.fn.applyStyle=this.support?t.fn.css:t.fn.animate,o.stop().applyStyle(i,t.extend(!0,[],{duration:e+"ms"}))}};var i=function(t){o.console&&o.console.error(t)};t.fn.hoverdir=function(o){var e=t.data(this,"hoverdir");if("string"==typeof o){var n=Array.prototype.slice.call(arguments,1);this.each(function(){return e?t.isFunction(e[o])&&"_"!==o.charAt(0)?void e[o].apply(e,n):void i("no such method '"+o+"' for hoverdir instance"):void i("cannot call methods on hoverdir prior to initialization; attempted to call method '"+o+"'")})}else this.each(function(){e?e._init():e=t.data(this,"hoverdir",new t.HoverDir(o,this))});return e}}(jQuery,window);